=== Osama-Almostafa/patientPlatform/src/main/java/Xml/aftaler.dtd
<!ELEMENT aftaler (aftale*)>
        <!ELEMENT aftale (info*)>


        <!ELEMENT info (cpr,date,time,hospital,adresse,læge)>
        <!ELEMENT cpr (#PCDATA)>
        <!ELEMENT date (#PCDATA)>
        <!ELEMENT time (#PCDATA)>
        <!ELEMENT hospital (#PCDATA)>
        <!ELEMENT adresse (#PCDATA)>
        <!ELEMENT læge (#PCDATA)>

=== Osama-Almostafa/patientPlatform/src/main/java/Xml/aftale.xml
<?xml version="1.0" encoding="UTF-8" ?>
<!DOCTYPE aftale SYSTEM "aftaler.dtd">
<aftale>
    <info>
        <cpr></cpr>
        <date></date>
        <time></time>
        <hospital></hospital>
        <afdeling></afdeling>
        <adresse></adresse>
    </info>
</aftale>
